import express from 'express';
import helmet from 'helmet';
import {rateLimit} from 'express-rate-limit';
import {readFileSync} from 'node:fs';
import {createHash,timingSafeEqual,randomUUID} from 'node:crypto';
import {join} from 'node:path';
import {canonicalCart,calculate,uuid,fail,AppError} from './validation.js';
import {cardPaymentSnapshot,cardPaymentChallenge,pixPaymentData} from './services/mercadopago.js';
import {authenticateWebhook} from './services/webhook.js';
import {addressInput,postalCode,deliveryHash,createShipping,createShippingProvider} from './services/shipping.js';
import {createNotifier} from './services/notifications.js';
import {renderHomeHtml,sitemapXml,robotsTxt} from './services/seo.js';
import {mountAdmin} from './admin.js';

const equal=(a,b)=>typeof a==='string'&&typeof b==='string'&&Buffer.byteLength(a)===Buffer.byteLength(b)&&timingSafeEqual(Buffer.from(a),Buffer.from(b));
const terminalStatus=new Set(['paid','cancelled','refunded','partially_refunded','failed','charged_back']);
const publicAnalyticsEvents=new Set(['page_view','product_view','add_to_cart']);
const supportedPaymentIntegrations=new Set(['cardform','payments-api']);
function publicOrder(o){return {orderId:o.orderId,orderCode:o.orderCode||String(o.orderId).slice(0,8).toUpperCase(),providerOrderId:o.providerOrderId||null,items:o.items,productsTotal:o.productsTotal,shipping:o.shipping,address:o.address,customer:o.customer?{customerId:o.customer.customerId,name:o.customer.name,email:o.customer.email,phone:o.customer.phone}:null,total:o.total,currency:o.currency,status:o.status,fulfillmentStatus:o.fulfillmentStatus||'awaiting_payment',fulfillmentHistory:Array.isArray(o.fulfillmentHistory)?o.fulfillmentHistory:[],trackingCode:o.trackingCode||'',createdAt:o.createdAt,paymentProvider:o.paymentProvider,paymentMethod:o.paymentMethod||'',paymentId:o.paymentId,providerStatusDetail:o.providerStatusDetail||'',providerUpdatedAt:o.providerUpdatedAt||null};}
function customerInput(raw){
  if(!raw||typeof raw!=='object'||Array.isArray(raw)||Object.keys(raw).sort().join(',')!=='email,name,phone')fail(400,'invalid_customer','Confira seus dados de contato.');
  const name=String(raw.name||'').trim().replace(/\s+/g,' '),email=String(raw.email||'').trim().toLowerCase(),phone=String(raw.phone||'').replace(/\D/g,'');
  if(name.length<2||name.length>100||/[<>\x00-\x1f\x7f]/.test(name))fail(400,'invalid_customer','Informe o nome para entrega.');
  if(email.length>254||!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email))fail(400,'invalid_customer','Informe um e-mail válido.');
  if(!/^\d{10,13}$/.test(phone))fail(400,'invalid_customer','Informe um WhatsApp com DDD.');
  return {name,email,phone};
}
function cardInput(raw){
  if(!raw||typeof raw!=='object'||Array.isArray(raw)||Object.keys(raw).sort().join(',')!=='email,identificationNumber,identificationType,installments,issuerId,paymentMethodId,token')fail(400,'invalid_card_data','Dados do pagamento inválidos.');
  const token=String(raw.token||''),issuerId=String(raw.issuerId||''),paymentMethodId=String(raw.paymentMethodId||''),email=String(raw.email||'').trim().toLowerCase(),identificationType=String(raw.identificationType||'').trim(),identificationNumber=String(raw.identificationNumber||'').trim(),installments=Number(raw.installments);
  if(!/^[A-Za-z0-9._-]{20,2048}$/.test(token))fail(400,'invalid_card_token','Token do cartão inválido.');
  if(issuerId&&!/^\d{1,24}$/.test(issuerId))fail(400,'invalid_issuer','Emissor do cartão inválido.');
  if(!/^[a-z0-9_-]{1,64}$/i.test(paymentMethodId))fail(400,'invalid_payment_method','Meio de pagamento inválido.');
  if(!Number.isInteger(installments)||installments<1||installments>24)fail(400,'invalid_installments','Número de parcelas inválido.');
  if(email.length>254||!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email))fail(400,'invalid_email','E-mail do pagador inválido.');
  if(!/^[A-Za-z0-9_-]{1,20}$/.test(identificationType)||!/^[A-Za-z0-9.\/-]{4,32}$/.test(identificationNumber))fail(400,'invalid_identification','Documento inválido.');
  return {token,issuerId,paymentMethodId,installments,email,identificationType,identificationNumber};
}
function pixInput(raw){
  if(!raw||typeof raw!=='object'||Array.isArray(raw)||Object.keys(raw).sort().join(',')!=='identificationNumber,identificationType')fail(400,'invalid_pix_data','Dados do Pix inválidos.');
  const identificationType=String(raw.identificationType||'').trim().toUpperCase(),identificationNumber=String(raw.identificationNumber||'').replace(/\D/g,'');
  if(!['CPF','CNPJ'].includes(identificationType))fail(400,'invalid_identification','Selecione CPF ou CNPJ.');
  if((identificationType==='CPF'&&!/^\d{11}$/.test(identificationNumber))||(identificationType==='CNPJ'&&!/^\d{14}$/.test(identificationNumber)))fail(400,'invalid_identification','Informe um documento válido para o Pix.');
  return {identificationType,identificationNumber};
}
function checkoutHash(cart,address,quote,customer){return createHash('sha256').update(deliveryHash(cart.hash,address,quote)+':'+quote.quoteId+':'+customer.customerId).digest('hex');}

export function createApp({config,catalog,store,gateway,shipping=createShipping(store,createShippingProvider()),logger=console}){
  const app=express();app.disable('x-powered-by');app.set('trust proxy',config.trustProxy||false);app.set('query parser','simple');
  const html=readFileSync(join(config.frontendPath,'index.html'),'utf8');
  const homeHtml=renderHomeHtml(html,{baseURL:config.baseURL,catalog});
  const cartScript=readFileSync(join(config.frontendPath,'js','cart.js'),'utf8');
  const cardPaymentScript=readFileSync(join(config.frontendPath,'js','card-payment.js'),'utf8');
  const pixPaymentScript=readFileSync(join(config.frontendPath,'js','pix-payment.js'),'utf8');
  const analyticsScript=readFileSync(join(config.frontendPath,'js','analytics.js'),'utf8');
  const notifier=createNotifier({config,store,logger});
  const hashes=tag=>[...homeHtml.matchAll(new RegExp(`<${tag}[^>]*>([\\s\\S]*?)<\\/${tag}>`,'g'))].map(m=>`'sha256-${createHash('sha256').update(m[1]).digest('base64')}'`);
  app.use(helmet({contentSecurityPolicy:{directives:{defaultSrc:["'self'"],scriptSrc:["'self'",'https://sdk.mercadopago.com','https://*.mlstatic.com',...hashes('script')],styleSrc:["'self'",...hashes('style')],imgSrc:["'self'",'data:','https://*.mercadopago.com','https://*.mercadopago.com.br','https://*.mlstatic.com'],fontSrc:["'self'",'data:'],connectSrc:["'self'",'https://viacep.com.br','https://api.mercadopago.com','https://*.mercadopago.com','https://*.mercadopago.com.br','https://*.mlstatic.com'],frameSrc:['https:'],objectSrc:["'none'"],baseUri:["'none'"],frameAncestors:["'none'"],formAction:["'self'",'https:'],upgradeInsecureRequests:config.production?[]:null}},referrerPolicy:{policy:'no-referrer'},hsts:config.production?{maxAge:31536000}:false}));
  app.use((req,res,next)=>{res.set('Cache-Control','no-store');if(config.production&&!req.secure)return res.status(400).json({error:'https_required',message:'Use HTTPS.'});if(req.get('origin')&&req.get('origin')!==config.baseURL)return res.status(403).json({error:'origin_forbidden',message:'Origem não permitida.'});next();});
  const limit=(n,windowMs=60000)=>rateLimit({windowMs,limit:n,standardHeaders:'draft-8',legacyHeaders:false,handler:(req,res)=>res.status(429).json({error:'rate_limited',message:'Muitas tentativas. Aguarde um minuto e tente novamente.'})});
  app.use('/api',limit(240));app.use(express.json({limit:'8kb',strict:true,type:'application/json'}));
  async function session(req,res,next){try{const raw=(req.get('cookie')||'').split(';').map(s=>s.trim()).find(s=>s.startsWith('jewelry_session='))?.slice('jewelry_session='.length);const current=await store.session(raw);if(!current)fail(401,'session_required','Abra novamente o carrinho para iniciar sua sessão.');req.shopSession=current;next();}catch(error){next(error);}}
  function mutation(req,res,next){if(!req.is('application/json'))fail(415,'json_required','Use JSON.');if(req.get('origin')!==config.baseURL)fail(403,'origin_forbidden','Origem não permitida.');if(!equal(req.get('x-csrf-token'),req.shopSession.csrf))fail(403,'csrf_invalid','Atualize a página para continuar.');next();}
  function assertBasePaymentReady(){if(config.mode==='production'&&config.durableStorage===false)fail(503,'persistent_storage_required','Pagamentos reais estão bloqueados até a loja usar armazenamento persistente compartilhado.');if(!config.webhookSecret||!shipping.configured)fail(503,'gateway_not_configured','O pagamento online ainda não está disponível.');}
  function assertCardReady(){assertBasePaymentReady();if(!gateway.cardConfigured||!config.publicKey)fail(503,'gateway_not_configured','O pagamento por cartão ainda não está disponível.');}
  function assertPixReady(){assertBasePaymentReady();if(!gateway.pixConfigured)fail(503,'pix_not_configured','O pagamento por Pix ainda não está disponível.');}
  function paymentFlowOk(order){return supportedPaymentIntegrations.has(order.gatewayPayload?.integration);}
  async function track(event,{path='/',productId=null,dedupeKey=null}={}){if(!config.analyticsEnabled||!store.recordAnalytics)return;try{await store.recordAnalytics({event,path,productId,dedupeKey});}catch(error){logger.error(JSON.stringify({event:'analytics_record_failed',code:String(error?.message||'analytics_error')}));}}
  async function flush(orderId){try{await notifier.flush(orderId);}catch(error){logger.error(JSON.stringify({event:'notification_flush_failed',orderId,code:String(error?.message||'notification_error')}));}}
  async function inventoryProducts(){
    if(!config.inventoryEnforcement||!store.listInventory)return catalog.map(p=>({...p}));
    const items=await store.listInventory(catalog),byId=new Map(items.map(item=>[item.productId,item]));
    return catalog.map(product=>{const stock=byId.get(product.productId),configured=Boolean(stock?.enabled&&Number.isInteger(stock.quantity)),available=configured?Math.max(0,stock.quantity):0,maxQuantity=configured?Math.min(Number(product.maxQuantity||available||1),available):0;return {...product,enabled:Boolean(product.enabled&&configured&&available>0),maxQuantity};});
  }
  async function reserveOrder(order,minExpiresAt=0){if(config.inventoryEnforcement){if(!store.reserveInventory)fail(503,'stock_not_configured','O controle de estoque não está disponível.');const quoteExpiry=Number.isFinite(order.quoteExpiresAt)?order.quoteExpiresAt:Date.now()+10*60*1000,expiresAt=Math.max(quoteExpiry,Number(minExpiresAt)||0);await store.reserveInventory(order.orderId,order.items,expiresAt);}}
  async function preparePaymentOrder(req,key){
    assertBasePaymentReady();
    if(!req.body||Object.keys(req.body).sort().join(',')!=='address,customer,items,quoteId')fail(400,'invalid_checkout','Envie somente items, customer, address e quoteId.');
    const cart=canonicalCart({items:req.body.items},catalog),address=addressInput(req.body.address),customerDetails=customerInput(req.body.customer);
    const quote=await shipping.get(req.shopSession.id,req.body.quoteId,cart,address.cep);if(Number.isFinite(quote.expiresAt)&&Date.now()>quote.expiresAt)fail(409,'shipping_quote_expired','A cotação de frete expirou. Calcule novamente antes de pagar.');
    const customer=await store.upsertCustomer(customerDetails),checkoutCart={...cart,hash:checkoutHash(cart,address,quote,customer)};let order=await store.findRequest(req.shopSession.id,key,checkoutCart.hash);
    if(!order){const totals=calculate(cart.items,catalog);totals.productsTotal=totals.total;totals.total+=quote.priceCents;if(!Number.isSafeInteger(totals.total)||totals.total<=0||totals.total>100000000)fail(400,'total_limit','Valor do pedido inválido.');totals.address=address;totals.customer=customer;totals.shipping={name:quote.name,serviceCode:quote.serviceCode,priceCents:quote.priceCents,days:quote.days,cep:quote.cep};totals.quoteExpiresAt=quote.expiresAt;order=await store.obtain(req.shopSession.id,key,checkoutCart,totals,()=>({integration:'payments-api'}));}
    if(!paymentFlowOk(order))fail(409,'payment_flow_mismatch','Este pedido pertence a outro fluxo de pagamento.');if(Date.now()-Date.parse(order.createdAt)>86400000)fail(409,'order_needs_review','Este pedido expirou. Calcule o frete novamente.');await reserveOrder(order);return order;
  }

  app.get('/api/health',limit(30),async(req,res)=>{try{const database=store.ping?await store.ping():true;const body={ok:Boolean(database),database:Boolean(database),storage:store.kind||'unknown',paymentMode:config.mode,shippingConfigured:Boolean(shipping.configured),adminConfigured:Boolean(config.adminConfigured),notificationsConfigured:Boolean(notifier.configured),analyticsEnabled:Boolean(config.analyticsEnabled),inventoryEnforcement:Boolean(config.inventoryEnforcement),cardConfigured:Boolean(gateway.cardConfigured&&config.publicKey),pixConfigured:Boolean(gateway.pixConfigured)};res.status(body.ok?200:503).json(body);}catch(error){logger.error(JSON.stringify({event:'health_check_failed',code:String(error?.message||'database_error')}));res.status(503).json({ok:false,database:false});}});
  app.post('/api/analytics',limit(60),async(req,res)=>{if(!config.analyticsEnabled)return res.status(204).end();if(!req.is('application/json')||!req.body||Object.keys(req.body).sort().join(',')!=='event,path,productId')fail(400,'invalid_analytics','Evento inválido.');const event=String(req.body.event||''),path=String(req.body.path||'/'),productId=String(req.body.productId||'');if(!publicAnalyticsEvents.has(event)||path.length>200||!/^[A-Za-z0-9_./-]*$/.test(path)||productId.length>80||!/^[A-Za-z0-9_-]*$/.test(productId))fail(400,'invalid_analytics','Evento inválido.');await track(event,{path,productId:productId||null});res.status(204).end();});
  app.get('/api/session',limit(config.sessionLimit),async(req,res)=>{const raw=(req.get('cookie')||'').split(';').map(s=>s.trim()).find(s=>s.startsWith('jewelry_session='))?.slice('jewelry_session='.length);let s=await store.session(raw);if(!s){s=await store.newSession();res.cookie('jewelry_session',s.raw,{httpOnly:true,secure:config.production,sameSite:'lax',path:'/',maxAge:7*86400000});}res.json({csrfToken:s.csrf});});
  app.get('/api/products',async(req,res)=>{const storageReady=config.mode!=='production'||config.durableStorage!==false,cardFormConfigured=Boolean(gateway.cardConfigured&&config.publicKey&&config.webhookSecret&&shipping.configured&&storageReady),pixConfigured=Boolean(gateway.pixConfigured&&config.webhookSecret&&shipping.configured&&storageReady),checkoutConfigured=cardFormConfigured||pixConfigured;res.json({currency:'BRL',products:await inventoryProducts(),shippingConfigured:shipping.configured,checkoutConfigured,cardFormConfigured,pixConfigured,paymentMode:'cardform+pix',paymentMethods:[...(cardFormConfigured?['card']:[]),...(pixConfigured?['pix']:[])],mercadoPagoPublicKey:cardFormConfigured?config.publicKey:'',inventoryEnforcement:Boolean(config.inventoryEnforcement)});});
  app.post('/api/shipping/quote',limit(15),session,mutation,async(req,res)=>{if(!req.body||Object.keys(req.body).sort().join(',')!=='cep,items')fail(400,'invalid_shipping','Envie somente items e cep.');const cart=canonicalCart({items:req.body.items},catalog),cep=postalCode(req.body.cep),options=await shipping.quote(req.shopSession.id,cart,cep);await track('shipping_quote',{path:'/api/shipping/quote'});res.json({options});});

  app.post('/api/card/prepare',limit(config.checkoutLimit),session,mutation,async(req,res)=>{assertCardReady();const key=req.get('idempotency-key');if(!uuid(key))fail(400,'idempotency_required','Identificador de tentativa inválido.');const order=await preparePaymentOrder(req,key);if(terminalStatus.has(order.status))fail(409,'order_terminal','Este pedido já possui um status final. Inicie uma nova tentativa.');await track('checkout_start',{path:'/api/card/prepare',dedupeKey:`checkout:${order.orderId}`});await flush(order.orderId);res.json({...publicOrder(order),amount:(order.total/100).toFixed(2),quoteExpiresAt:order.quoteExpiresAt});});
  app.post('/api/card/pay',limit(config.checkoutLimit),session,mutation,async(req,res)=>{
    const key=req.get('idempotency-key');if(!uuid(key))fail(400,'idempotency_required','Identificador de tentativa inválido.');if(!req.body||Object.keys(req.body).sort().join(',')!=='card,orderId'||!uuid(req.body.orderId))fail(400,'invalid_payment','Envie somente orderId e card.');assertCardReady();
    const card=cardInput(req.body.card);let order=await store.get(req.body.orderId);if(!order||order.owner!==req.shopSession.id)fail(404,'order_not_found','Pedido não encontrado para esta sessão.');if(!paymentFlowOk(order))fail(409,'payment_flow_mismatch','Este pedido pertence a outro fluxo de pagamento.');if(order.customer?.email&&card.email!==String(order.customer.email).toLowerCase())fail(409,'customer_email_mismatch','Use o mesmo e-mail informado nos dados do cliente.');if(Date.now()-Date.parse(order.createdAt)>86400000)fail(409,'order_needs_review','Este pedido expirou. Calcule o frete novamente.');if(order.paymentMethod&&order.paymentMethod!=='card'&&(order.paymentAttemptKey||order.providerOrderId))fail(409,'payment_method_locked','Este pedido já iniciou pagamento por outro meio.');if(order.status==='paid'){await flush(order.orderId);return res.json({...publicOrder(order),providerStatus:'approved',providerStatusDetail:order.providerStatusDetail||'accredited'});}if(terminalStatus.has(order.status)){await flush(order.orderId);return res.json({...publicOrder(order),providerStatus:order.status,providerStatusDetail:order.providerStatusDetail||''});}
    await reserveOrder(order);await track('payment_start',{path:'/api/card/pay',dedupeKey:`payment-start:${order.orderId}`});
    let remote;if(order.providerOrderId&&/^\d+$/.test(String(order.providerOrderId))){remote=await gateway.getPayment(String(order.providerOrderId));}else{if(Number.isFinite(order.quoteExpiresAt)&&Date.now()>order.quoteExpiresAt)fail(409,'shipping_quote_expired','A cotação de frete expirou. Volte ao carrinho e calcule o frete novamente.');if(order.paymentAttemptKey&&order.paymentAttemptKey!==key)fail(409,'payment_in_progress','Já existe uma tentativa de pagamento em andamento para este pedido.');if(!order.paymentAttemptKey){order.paymentAttemptKey=key;order.paymentMethod='card';await store.save(order);}remote=await gateway.createCardPayment(order,card,key);}
    const snapshot=cardPaymentSnapshot(remote,order,gateway);await store.applySnapshot(order.orderId,snapshot);order=await store.get(order.orderId);if(order.status==='paid')await track('purchase',{path:'/api/card/pay',dedupeKey:`purchase:${order.orderId}`});await flush(order.orderId);res.json({...publicOrder(order),providerStatus:String(remote.status||''),providerStatusDetail:String(remote.status_detail||''),threeDs:cardPaymentChallenge(remote)});
  });

  app.post('/api/pix/prepare',limit(config.checkoutLimit),session,mutation,async(req,res)=>{assertPixReady();const key=req.get('idempotency-key');if(!uuid(key))fail(400,'idempotency_required','Identificador de tentativa inválido.');const order=await preparePaymentOrder(req,key);if(terminalStatus.has(order.status))fail(409,'order_terminal','Este pedido já possui um status final. Inicie uma nova tentativa.');await track('checkout_start',{path:'/api/pix/prepare',dedupeKey:`checkout:${order.orderId}`});await flush(order.orderId);res.json({...publicOrder(order),amount:(order.total/100).toFixed(2),quoteExpiresAt:order.quoteExpiresAt});});
  app.post('/api/pix/pay',limit(config.checkoutLimit),session,mutation,async(req,res)=>{
    const key=req.get('idempotency-key');if(!uuid(key))fail(400,'idempotency_required','Identificador de tentativa inválido.');if(!req.body||Object.keys(req.body).sort().join(',')!=='identification,orderId'||!uuid(req.body.orderId))fail(400,'invalid_payment','Envie somente orderId e identification.');assertPixReady();
    const payer=pixInput(req.body.identification);let order=await store.get(req.body.orderId);if(!order||order.owner!==req.shopSession.id)fail(404,'order_not_found','Pedido não encontrado para esta sessão.');if(!paymentFlowOk(order))fail(409,'payment_flow_mismatch','Este pedido pertence a outro fluxo de pagamento.');if(Date.now()-Date.parse(order.createdAt)>86400000)fail(409,'order_needs_review','Este pedido expirou. Calcule o frete novamente.');if(order.paymentMethod&&order.paymentMethod!=='pix'&&(order.paymentAttemptKey||order.providerOrderId))fail(409,'payment_method_locked','Este pedido já iniciou pagamento por outro meio.');if(order.status==='paid'){await flush(order.orderId);return res.json({...publicOrder(order),providerStatus:'approved',providerStatusDetail:order.providerStatusDetail||'accredited',pix:null});}if(terminalStatus.has(order.status)){await flush(order.orderId);return res.json({...publicOrder(order),providerStatus:order.status,providerStatusDetail:order.providerStatusDetail||'',pix:null});}
    if(Number.isFinite(order.quoteExpiresAt)&&Date.now()>order.quoteExpiresAt)fail(409,'shipping_quote_expired','A cotação de frete expirou. Volte ao carrinho e calcule o frete novamente.');await reserveOrder(order,Date.now()+30*60*1000);await track('payment_start',{path:'/api/pix/pay',dedupeKey:`payment-start:${order.orderId}`});
    let remote;if(order.providerOrderId&&/^\d+$/.test(String(order.providerOrderId))){remote=await gateway.getPayment(String(order.providerOrderId));}else{if(order.paymentAttemptKey&&order.paymentAttemptKey!==key)fail(409,'payment_in_progress','Já existe uma tentativa de pagamento em andamento para este pedido.');if(!order.paymentAttemptKey){order.paymentAttemptKey=key;order.paymentMethod='pix';await store.save(order);}remote=await gateway.createPixPayment(order,payer,key);}
    const snapshot=cardPaymentSnapshot(remote,order,gateway);await store.applySnapshot(order.orderId,snapshot);order=await store.get(order.orderId);if(order.status==='paid')await track('purchase',{path:'/api/pix/pay',dedupeKey:`purchase:${order.orderId}`});await flush(order.orderId);res.json({...publicOrder(order),providerStatus:String(remote.status||''),providerStatusDetail:String(remote.status_detail||''),pix:pixPaymentData(remote)});
  });

  app.get('/api/orders/:orderId',limit(30),session,async(req,res)=>{if(!uuid(req.params.orderId))fail(404,'order_not_found','Pedido não encontrado.');let order=await store.get(req.params.orderId),remote=null;if(!order||order.owner!==req.shopSession.id)fail(404,'order_not_found','Pedido não encontrado para esta sessão.');if(['pending','processing','paid','partially_refunded','in_mediation'].includes(order.status)&&/^\d+$/.test(String(order.providerOrderId||''))){try{remote=await gateway.getPayment(String(order.providerOrderId));await store.applySnapshot(order.orderId,cardPaymentSnapshot(remote,order,gateway));order=await store.get(order.orderId);if(order.status==='paid')await track('purchase',{path:'/api/orders',dedupeKey:`purchase:${order.orderId}`});await flush(order.orderId);}catch(error){logger.error(JSON.stringify({event:'order_reconciliation_failed',orderId:order.orderId,providerOrderId:order.providerOrderId,code:error instanceof AppError?error.code:'gateway_error'}));}}res.json({...publicOrder(order),pix:pixPaymentData(remote)});});
  app.post('/api/webhooks/mercadopago',limit(config.webhookLimit),async(req,res)=>{if(!req.is('application/json'))fail(415,'json_required','Use JSON.');const providerId=authenticateWebhook(req,config.webhookSecret);if(req.body.application_id!==undefined&&String(req.body.application_id)!==String(config.applicationId))fail(409,'webhook_application_mismatch','Aplicação da notificação não corresponde à loja.');if(req.body.user_id!==undefined&&String(req.body.user_id)!==String(config.sellerId))fail(409,'webhook_seller_mismatch','Vendedor da notificação não corresponde à loja.');if(req.body.live_mode!==undefined&&req.body.live_mode!==(config.mode==='production'))fail(409,'webhook_mode_mismatch','Ambiente da notificação não corresponde à loja.');const remote=await gateway.getPayment(providerId);if(!uuid(remote.external_reference))fail(409,'unknown_order','Pedido não reconhecido.');const order=await store.get(remote.external_reference);if(!order)fail(409,'unknown_order','Pedido não reconhecido.');if(order.providerOrderId&&String(order.providerOrderId)!==String(remote.id))fail(409,'provider_id_mismatch','Pagamento não associado a este pedido.');await store.applySnapshot(order.orderId,cardPaymentSnapshot(remote,order,gateway));const saved=await store.get(order.orderId);if(saved?.status==='paid')await track('purchase',{path:'/api/webhooks/mercadopago',dedupeKey:`purchase:${saved.orderId}`});await flush(order.orderId);res.status(200).json({received:true});});

  mountAdmin(app,{config,store,limit,catalog,notifier});
  app.get('/js/cart.js',(req,res)=>{res.type('application/javascript').send(analyticsScript+'\n'+cartScript+'\n'+cardPaymentScript+'\n'+pixPaymentScript);});
  app.get('/sitemap.xml',(req,res)=>res.type('application/xml').send(sitemapXml(config.baseURL)));
  app.get('/robots.txt',(req,res)=>res.type('text/plain').send(robotsTxt(config.baseURL)));
  app.get('/',(req,res)=>res.type('html').send(homeHtml));
  app.get(['/sucesso','/sucesso.html'],(req,res)=>res.sendFile(join(config.frontendPath,'sucesso.html')));
  app.get(['/admin','/admin/'],(req,res)=>res.sendFile(join(config.frontendPath,'admin','index.html')));
  app.use(express.static(config.frontendPath,{dotfiles:'deny',index:'index.html',redirect:false,etag:false}));
  app.use((req,res)=>res.status(404).json({error:'not_found',message:'Recurso não encontrado.'}));
  app.use((error,req,res,next)=>{if(res.headersSent)return next(error);if(error.type==='entity.parse.failed')return res.status(400).json({error:'invalid_json',message:'JSON malformado.'});if(error.type==='entity.too.large')return res.status(413).json({error:'body_too_large',message:'Requisição muito grande.'});if(error instanceof AppError){if(error.status>=500)logger.error(JSON.stringify({event:'app_error',path:req.path,method:req.method,code:error.code,status:error.status}));return res.status(error.status).json({error:error.code,message:error.message});}const incident=randomUUID();logger.error(JSON.stringify({event:'internal_error',incident,path:req.path,method:req.method}));res.status(500).json({error:'internal_error',message:'Não foi possível concluir a operação.',incident});});
  return app;
}
