import test from 'node:test';
import assert from 'node:assert/strict';
import {randomUUID,createHmac} from 'node:crypto';
import {mkdtempSync,rmSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join,resolve} from 'node:path';
import request from 'supertest';
import {createApp} from '../backend/app.js';
import {openStore} from '../backend/store.js';
import {createGateway,checkoutPayload,paymentSnapshot} from '../backend/services/mercadopago.js';
import {canonicalCart,calculate,money,cents} from '../backend/validation.js';
import {readConfig} from '../backend/config.js';
// Artificial amounts used ONLY by automated tests, never by the public catalog.
const products=()=>Array.from({length:5},(_,i)=>({productId:`produto_0${i+1}`,name:`Test item ${i+1}`,priceCents:19990+i*1000,enabled:true,maxQuantity:10}));
const body={items:[{productId:'produto_01',quantity:2},{productId:'produto_02',quantity:1}]};
const providerId='ORDTST1234567890123456789012';
const providerURL='https://www.mercadopago.com.br/checkout/v1/redirect?pref_id=test-only';
async function fixture(t,overrides={}){
 const config={...readConfig({}),frontendPath:resolve('frontend'),baseURL:'https://loja.example',webhookSecret:'test-signature-secret',checkoutLimit:100,...overrides};
 const catalog=products(),store=openStore(':memory:');t.after(()=>store.close());
 let creates=0,gets=0,remote,failNext=false;const submissions=[];
 const real=createGateway({accessToken:'test-only-not-a-credential',sellerId:'123',applicationId:'456',baseURL:config.baseURL,mode:'test'});
 const gateway={configured:true,verifyIdentity:real.verifyIdentity,
  async create(order){creates++;submissions.push(structuredClone(order));await new Promise(r=>setTimeout(r,4));if(failNext){failNext=false;throw Error('simulated provider timeout');}remote={id:providerId,external_reference:order.orderId,type:'online',processing_mode:'manual',currency:'BRL',country_code:'BRA',user_id:123,integration_data:{application_id:456},total_amount:money(order.total),total_paid_amount:'0.00',status:'created',status_detail:'created',last_updated_date:new Date().toISOString(),items:order.gatewayPayload.items};return {providerOrderId:providerId,checkoutUrl:providerURL};},
  async get(){gets++;return structuredClone(remote);}};
 // Isolate the original payment suite from delivery; real freight is covered in shipping.test.js.
 const shipping={configured:true,get(){return {serviceCode:'03298',priceCents:0,name:'Test delivery',cep:'01001000',days:3};}};
 const app=createApp({config,catalog,store,gateway,shipping,logger:{error(){}}}),agent=request.agent(app);
 const session=await agent.get('/api/session').expect(200);const csrf=session.body.csrfToken;
 const checkout=(payload=body,key=randomUUID())=>agent.post('/api/checkout').set('Origin',config.baseURL).set('X-CSRF-Token',csrf).set('Idempotency-Key',key).send({address:{cep:'01001000',street:'Rua Teste',number:'1',complement:'',district:'Centro',city:'São Paulo',state:'SP'},quoteId:'test-only',...payload});
 function webhook({ts=String(Math.floor(Date.now()/1000)),id=providerId,signature,notification,requestId='test-request-12345'}={}){const digest=createHmac('sha256',config.webhookSecret).update(`id:${id};request-id:${requestId};ts:${ts};`).digest('hex');return request(app).post('/api/webhooks/mercadopago?data.id='+id).set('x-request-id',requestId).set('x-signature',signature||`ts=${ts},v1=${digest}`).send(notification||{type:'order',data:{id},status:'paid'});}
 return {app,agent,config,catalog,store,gateway,csrf,checkout,webhook,session,submissions,get creates(){return creates;},get gets(){return gets;},get remote(){return remote;},set remote(v){remote=v;},failNext(){failNext=true;}};
}
test('authoritative cents, persisted pending order, private snapshot and server-only payload',async t=>{
 const f=await fixture(t);const r=await f.checkout().expect(200);assert.equal(r.body.total,60970);assert.equal(r.body.status,'pending');assert.equal(r.body.items[0].unitPrice,19990);assert.match(r.body.orderId,/^[\da-f-]{36}$/);assert.equal(r.body.owner,undefined);assert.equal(r.body.gatewayPayload,undefined);const o=f.store.get(r.body.orderId);assert.equal(o.gatewayPayload.total_amount,'609.70');assert.equal(o.gatewayPayload.external_reference,o.orderId);assert.equal(o.paymentId,null);assert.equal(f.store.db.prepare('SELECT count(*) n FROM orders').get().n,1);
});
for(const [name,payload] of [
 ['empty',{items:[]}],['missing items',{}],['zero',{items:[{productId:'produto_01',quantity:0}]}],['negative',{items:[{productId:'produto_01',quantity:-1}]}],['fraction',{items:[{productId:'produto_01',quantity:1.5}]}],['string quantity',{items:[{productId:'produto_01',quantity:'2'}]}],['extreme',{items:[{productId:'produto_01',quantity:999999999}]}],['unknown ID',{items:[{productId:'produto_06',quantity:1}]}],['duplicate IDs',{items:[{productId:'produto_01',quantity:1},{productId:'produto_01',quantity:1}]}],['fake price',{items:[{productId:'produto_01',quantity:1,price:1}]}],['fake total',{...body,total:1}],['fake discount',{...body,discount:100}],['fake paymentStatus',{...body,paymentStatus:'paid'}]
])test(`reject ${name} without creating an order`,async t=>{const f=await fixture(t);await f.checkout(payload).expect(400);assert.equal(f.creates,0);assert.equal(f.store.db.prepare('SELECT count(*) n FROM orders').get().n,0);});
test('malformed JSON and oversized payload rejected',async t=>{const f=await fixture(t);await f.agent.post('/api/checkout').set('Content-Type','application/json').send('{bad').expect(400);await f.agent.post('/api/checkout').set('Content-Type','application/json').send(JSON.stringify({data:'x'.repeat(9000)})).expect(413);assert.equal(f.creates,0);});
test('unpriced, unavailable, missing credentials fail closed',async t=>{const f=await fixture(t);f.catalog[0].priceCents=null;await f.checkout().expect(503);f.catalog[0].enabled=false;await f.checkout().expect(409);f.catalog[0].enabled=true;f.catalog[0].priceCents=19990;f.gateway.configured=false;await f.checkout().expect(503);assert.equal(f.creates,0);});
test('session, origin, CSRF including multibyte input and idempotency key required',async t=>{const f=await fixture(t);await request(f.app).post('/api/checkout').send(body).expect(401);await f.agent.post('/api/checkout').send(body).expect(403);await f.agent.post('/api/checkout').set('Origin','https://attacker.example').send(body).expect(403);await f.agent.post('/api/checkout').set('Origin',f.config.baseURL).set('x-csrf-token','é'.repeat(64)).send(body).expect(403);await f.agent.post('/api/checkout').set('Origin',f.config.baseURL).set('x-csrf-token',f.csrf).send(body).expect(400);assert.match(f.session.headers['set-cookie'][0],/HttpOnly/);assert.match(f.session.headers['set-cookie'][0],/SameSite=Lax/);});
test('parallel clicks, reload/new keys and repeated attempts reuse one order',async t=>{const f=await fixture(t);const key=randomUUID();const results=await Promise.all([f.checkout(body,key),f.checkout(body,key),f.checkout(body)]);for(const r of results)assert.equal(r.status,200);assert.equal(new Set(results.map(r=>r.body.orderId)).size,1);assert.equal(f.creates,1);assert.equal(f.store.db.prepare('SELECT count(*) n FROM orders').get().n,1);await f.checkout({items:[{productId:'produto_01',quantity:1}]},key).expect(409);});
test('provider timeout retry preserves order, gateway key and original price snapshot',async t=>{const f=await fixture(t);const key=randomUUID();f.failNext();await f.checkout(body,key).expect(500);f.catalog[0].priceCents=1;const r=await f.checkout(body,key).expect(200);assert.equal(r.body.total,60970);assert.equal(f.creates,2);assert.deepEqual(f.submissions[0].gatewayPayload,f.submissions[1].gatewayPayload);assert.equal(f.submissions[0].orderId,f.submissions[1].orderId);});
test('private order access and direct success URL never confirm payment',async t=>{const f=await fixture(t);const r=await f.checkout().expect(200),id=r.body.orderId;await request(f.app).get('/api/orders/'+id).expect(401);const other=request.agent(f.app);await other.get('/api/session');await other.get('/api/orders/'+id).expect(404);await f.agent.get('/sucesso?orderId='+id+'&status=approved&paymentStatus=paid').expect(200);const state=await f.agent.get('/api/orders/'+id).expect(200);assert.equal(state.body.status,'pending');assert.equal(f.gets,1);assert.equal(f.store.db.prepare('SELECT count(*) n FROM outbox').get().n,0);});
test('rate limit blocks rapid checkout requests',async t=>{const f=await fixture(t,{checkoutLimit:3});for(let i=0;i<3;i++)await f.checkout({items:[]}).expect(400);await f.checkout().expect(429);assert.equal(f.creates,0);});
test('security headers, secret paths and HTTPS enforcement',async t=>{const f=await fixture(t);const r=await f.agent.get('/').expect(200);assert.match(r.headers['content-security-policy'],/frame-ancestors 'none'/);assert.match(r.headers['content-security-policy'],/sha256-/);assert.equal(r.headers['x-content-type-options'],'nosniff');for(const path of ['/.env','/backend/products.js','/backend/data/shop.sqlite','/node_modules/express/package.json'])await f.agent.get(path).expect(404);const app=createApp({config:{...f.config,production:true,trustProxy:false},catalog:f.catalog,store:f.store,gateway:f.gateway});await request(app).get('/api/products').set('x-forwarded-proto','https').expect(400);});
test('signed repeated webhook verifies provider and creates one fulfillment event',async t=>{const f=await fixture(t);const r=await f.checkout().expect(200);f.remote={...f.remote,status:'processed',status_detail:'accredited',total_paid_amount:'609.70',transactions:{payments:[{id:'123456',status:'processed'}]}};for(let i=0;i<3;i++)await f.webhook().expect(200);assert.equal(f.gets,3);assert.equal(f.store.get(r.body.orderId).status,'paid');assert.equal(f.store.get(r.body.orderId).paymentId,'123456');assert.equal(f.store.db.prepare('SELECT count(*) n FROM outbox').get().n,1);assert.equal(f.store.db.prepare('SELECT count(*) n FROM events').get().n,1);});
test('millisecond signature supported; unsigned body paid is never authoritative',async t=>{const f=await fixture(t);const r=await f.checkout().expect(200);await f.webhook({ts:String(Date.now())}).expect(200);assert.equal(f.store.get(r.body.orderId).status,'pending');});
test('bad, missing, expired signature and mismatched IDs rejected before provider lookup',async t=>{const f=await fixture(t);await f.checkout().expect(200);await f.webhook({signature:'ts=1000000000,v1=bad'}).expect(401);await f.webhook({ts:String(Math.floor(Date.now()/1000)-600)}).expect(401);await f.webhook({notification:{type:'order',data:{id:'ORDWRONG1234567890'}}}).expect(400);await request(f.app).post('/api/webhooks/mercadopago').send({}).expect(400);assert.equal(f.gets,0);});
for(const [name,change]of [
 ['amount',{total_amount:'0.01'}],['underpayment',{total_paid_amount:'0.01'}],['currency',{currency:'USD'}],['seller',{user_id:999}],['application',{integration_data:{application_id:999}}],['external reference',{external_reference:randomUUID()}],['provider ID',{id:'ORDTST99999999999999999'}],['environment',{live_mode:true}]
])test(`webhook rejects wrong ${name}`,async t=>{const f=await fixture(t);const r=await f.checkout().expect(200);f.remote={...f.remote,status:'processed',status_detail:'accredited',total_paid_amount:'609.70',...change};await f.webhook().expect(409);assert.equal(f.store.get(r.body.orderId).status,'pending');assert.equal(f.store.db.prepare('SELECT count(*) n FROM outbox').get().n,0);});
test('out-of-order events cannot downgrade paid; refund blocks pending fulfillment once',async t=>{const f=await fixture(t);const r=await f.checkout().expect(200),id=r.body.orderId;const now=Date.now();f.remote={...f.remote,status:'processed',status_detail:'accredited',total_paid_amount:'609.70',last_updated_date:new Date(now).toISOString()};await f.webhook().expect(200);f.remote={...f.remote,status:'created',status_detail:'created',last_updated_date:new Date(now-10000).toISOString()};await f.webhook().expect(200);assert.equal(f.store.get(id).status,'paid');f.remote={...f.remote,status:'processed',status_detail:'refunded',last_updated_date:new Date(now+1000).toISOString()};await f.webhook().expect(200);await f.webhook().expect(200);assert.equal(f.store.get(id).status,'refunded');assert.equal(f.store.db.prepare('SELECT state FROM outbox').get().state,'blocked');assert.equal(f.store.db.prepare('SELECT count(*) n FROM outbox').get().n,1);});
test('SQLite survives close/reopen with sessions, request keys and immutable orders',()=>{const dir=mkdtempSync(join(tmpdir(),'jewelry-test-'));try{const path=join(dir,'shop.sqlite');let s=openStore(path);const session=s.newSession(),key=randomUUID(),cart=canonicalCart(body,products());const order=s.obtain(session.id,key,cart,calculate(cart.items,products()),o=>checkoutPayload(o,'https://loja.example'));s.close();s=openStore(path);assert.equal(s.session(session.raw).id,session.id);assert.equal(s.findRequest(session.id,key,cart.hash).orderId,order.orderId);assert.equal(s.get(order.orderId).total,60970);s.close();}finally{rmSync(dir,{recursive:true,force:true});}});
test('real adapter uses official Orders API, backend bearer token and durable idempotency key',async()=>{const order={orderId:randomUUID(),...calculate(body.items,products())};order.gatewayPayload=checkoutPayload(order,'https://loja.example');const calls=[];const response={id:providerId,external_reference:order.orderId,type:'online',processing_mode:'manual',currency:'BRL',country_code:'BRA',user_id:123,integration_data:{application_id:456},total_amount:'609.70',checkout_url:providerURL};const gateway=createGateway({accessToken:'test-only-token',sellerId:'123',applicationId:'456',baseURL:'https://loja.example',mode:'test',fetchImpl:async(url,options)=>{calls.push({url,options});return {ok:true,text:async()=>JSON.stringify(response)};}});const result=await gateway.create(order);assert.equal(result.providerOrderId,providerId);assert.equal(calls[0].url,'https://api.mercadopago.com/v1/orders');assert.equal(calls[0].options.headers['X-Idempotency-Key'],order.orderId);assert.equal(calls[0].options.headers.Authorization,'Bearer test-only-token');assert.equal(JSON.parse(calls[0].options.body).total_amount,'609.70');await gateway.get(providerId);assert.equal(calls[1].url,'https://api.mercadopago.com/v1/orders/'+providerId);});
test('config rejects insecure production and broad proxy trust; exact money conversion',()=>{assert.throws(()=>readConfig({NODE_ENV:'production',APP_URL:'http://loja.example'}));assert.throws(()=>readConfig({TRUST_PROXY:'true'}));assert.throws(()=>readConfig({MERCADO_PAGO_MODE:'production'}));assert.equal(cents('199.90'),19990);assert.equal(money(19990),'199.90');assert.equal(createGateway({mode:'disabled',accessToken:'x',sellerId:'123',applicationId:'456',baseURL:'https://loja.example'}).configured,false);});
