import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {randomUUID} from 'node:crypto';
import {JSDOM} from 'jsdom';
const html=readFileSync('frontend/index.html','utf8'),model=readFileSync('frontend/js/cart-model.js','utf8'),script=readFileSync('frontend/js/cart.js','utf8');
const products=Array.from({length:5},(_,i)=>({productId:`produto_0${i+1}`,name:`Peça teste ${i+1}`,priceCents:19990+i*1000,enabled:true,maxQuantity:10}));
const deliveryAddress={cep:'01001000',street:'Praça da Sé',number:'1',complement:'',district:'Sé',city:'São Paulo',state:'SP'};
const quoteId='11111111-1111-4111-8111-111111111111';
async function prepareShipping(p){for(const [key,value] of Object.entries(deliveryAddress))p.d.querySelector('#delivery-form [name="'+key+'"]').value=value;p.d.querySelector('#shipping-calculate').click();await tick();const radio=p.d.querySelector('[name="shipping-choice"]');radio.checked=true;radio.dispatchEvent(new p.w.Event('change',{bubbles:true}));}
const tick=()=>new Promise(r=>setTimeout(r,0));
test('HTTPS preview without backend displays R$150 per unit and visual total without allowing payment',async t=>{
 const p=await page(t,{error:true});p.add('produto_01');p.add('produto_01');p.add('produto_02');
 assert.match(p.d.querySelector('#cart-total').textContent,/450,00/);
 assert.match(p.d.querySelector('#cart-lines').textContent,/150,00/);
 assert.equal(p.d.querySelector('#cart-checkout').disabled,true);
 assert.equal(p.d.querySelectorAll('[data-product-price]').length,5);
 assert.match(p.d.querySelector('[data-product-price]').textContent,/150,00/);
});
test('shipping selection shows total and changes to CEP or cart invalidate quote; address is not stored',async t=>{
 const p=await page(t);p.add('produto_01');await prepareShipping(p);
 assert.match(p.d.querySelector('#grand-total').textContent,/223,35/);assert.equal(p.d.querySelector('#cart-checkout').disabled,false);
 assert.deepEqual(p.stored(),{items:[{productId:'produto_01',quantity:1}]});
 p.d.querySelector('#delivery-cep').value='20040020';p.d.querySelector('#delivery-cep').dispatchEvent(new p.w.Event('input',{bubbles:true}));
 assert.equal(p.d.querySelector('#cart-checkout').disabled,true);assert.match(p.d.querySelector('#shipping-total').textContent,/calcular/);
 await prepareShipping(p);p.add('produto_02');assert.equal(p.d.querySelector('#cart-checkout').disabled,true);
});
test('checkout requires complete delivery address',async t=>{
 const p=await page(t);p.add('produto_01');await prepareShipping(p);p.d.querySelector('[name="street"]').value='';p.d.querySelector('#cart-checkout').click();await tick();assert.equal(p.calls.filter(c=>c.url==='/api/checkout').length,0);
});
async function page(t,{saved,catalog=products,configured=true,offline=false,error=false}={}){
 const dom=new JSDOM(html,{url:offline?'file:///jewelry-referencia.html':'https://loja.example',runScripts:'outside-only'}),w=dom.window,d=w.document;t.after(()=>w.close());
 w.matchMedia=()=>({matches:false});w.HTMLDialogElement.prototype.showModal=function(){this.open=true;};w.HTMLDialogElement.prototype.close=function(){this.open=false;this.dispatchEvent(new w.Event('close'));};
 const calls=[];w.fetch=async(url,options={})=>{calls.push({url,options});if(error)throw Error('Falha de conexão');return {ok:true,json:async()=>url==='/api/session'?{csrfToken:'test-csrf'}:url==='/api/shipping/quote'?{options:[{quoteId,name:'Correios PAC',priceCents:2345,days:4,expiresAt:Date.now()+600000}]}:url==='/api/products'?{products:catalog,checkoutConfigured:configured}: {orderId:randomUUID(),status:'pending',total:39980,items:[{productId:'produto_01',name:'Preço do servidor',quantity:2,unitPrice:19990,subtotal:39980}],checkoutUrl:'https://www.mercadopago.com.br/checkout/v1/redirect?test=1'}};};
 if(saved!==undefined)w.localStorage.setItem('jewelry.cart.v1',saved);
 d.querySelectorAll('script:not([src])').forEach(el=>w.eval(el.textContent));w.eval(model);w.eval(script);await tick();
 return {w,d,calls,stored:()=>JSON.parse(w.localStorage.getItem('jewelry.cart.v1')),add:id=>d.querySelector(`[data-add-product="${id}"]`).click(),open:()=>d.querySelector('#cart-toggle').click()};
}
test('add different and same products, quantities, totals, remove, empty and reload',async t=>{const p=await page(t);p.add('produto_01');p.add('produto_02');p.add('produto_01');assert.equal(p.d.querySelector('#cart-count').textContent,'3');assert.deepEqual(p.stored().items,[{productId:'produto_01',quantity:2},{productId:'produto_02',quantity:1}]);p.open();assert.equal(p.d.querySelector('#cart-drawer').open,true);assert.match(p.d.querySelector('#cart-total').textContent,/609,70/);const plus=p.d.querySelector('[data-cart-focus="produto_01-plus"]');plus.focus();plus.click();assert.equal(p.stored().items[0].quantity,3);assert.equal(p.d.activeElement.dataset.cartFocus,'produto_01-plus');p.d.querySelector('[data-cart-focus="produto_01-minus"]').click();assert.equal(p.stored().items[0].quantity,2);
 const reloaded=await page(t,{saved:JSON.stringify(p.stored())});assert.equal(reloaded.d.querySelector('#cart-count').textContent,'3');p.d.querySelector('[data-cart-focus="produto_02-remove"]').click();assert.equal(p.stored().items.length,1);p.d.querySelector('#cart-clear').click();assert.deepEqual(p.stored(),{items:[]});assert.equal(p.d.querySelector('#cart-empty').hidden,false);p.d.querySelector('#cart-continue').click();assert.equal(p.d.querySelector('#cart-drawer').open,false);
});
for(const quantity of [0,-1,1.2,100000000])test(`quantity input rejects ${quantity}`,async t=>{const p=await page(t);p.add('produto_01');p.open();const input=p.d.querySelector('.cart-quantity input');input.value=quantity;input.dispatchEvent(new p.w.Event('change'));assert.equal(p.stored().items[0].quantity,1);assert.match(p.d.querySelector('#cart-message').textContent,/inteira/);assert.equal(p.d.querySelector('[data-cart-focus="produto_01-minus"]').disabled,true);});
test('maximum quantity is enforced by repeated add and plus buttons',async t=>{const p=await page(t);for(let i=0;i<20;i++)p.add('produto_01');assert.equal(p.stored().items[0].quantity,10);assert.equal(p.d.querySelector('[data-cart-focus="produto_01-plus"]').disabled,true);assert.match(p.d.querySelector('#cart-toast').textContent,/limite/);});
test('localStorage strips fake prices/status and unknown or invalid items',async t=>{const p=await page(t,{saved:JSON.stringify({total:1,paymentStatus:'paid',items:[{productId:'produto_01',quantity:2,price:1,total:1},{productId:'produto_99',quantity:1},{productId:'produto_02',quantity:0},{productId:'produto_03',quantity:-1},{productId:'produto_04',quantity:1e8}]})});assert.deepEqual(p.stored(),{items:[{productId:'produto_01',quantity:2}]});assert.match(p.d.querySelector('#cart-total').textContent,/399,80/);assert.equal(p.d.querySelector('#cart-review').hidden,true);});
test('malformed localStorage recovers safely',async t=>{const p=await page(t,{saved:'{malformed'});assert.deepEqual(p.stored(),{items:[]});assert.equal(p.d.querySelector('#cart-empty').hidden,false);});
test('DOM/DevTools price tampering never enters checkout request; review uses server prices',async t=>{const p=await page(t);p.add('produto_01');p.add('produto_01');await prepareShipping(p);p.d.querySelector('.piece-note').textContent='R$ 0,01';p.d.querySelector('#cart-total').textContent='R$ 0,01';p.d.querySelector('#cart-checkout').click();await tick();const sent=p.calls.find(c=>c.url==='/api/checkout');assert.deepEqual(JSON.parse(sent.options.body),{items:[{productId:'produto_01',quantity:2}],address:deliveryAddress,quoteId});assert.equal(sent.options.headers['X-CSRF-Token'],'test-csrf');assert.match(sent.options.headers['Idempotency-Key'],/^[\da-f-]{36}$/);assert.match(p.d.querySelector('#checkout-review-total').textContent,/399,80/);assert.equal(p.d.querySelector('#cart-review').hidden,false);assert.equal(p.stored().items[0].quantity,2);p.d.querySelector('#cart-checkout').click();await tick();const attempts=p.calls.filter(c=>c.url==='/api/checkout');assert.equal(attempts[0].options.headers['Idempotency-Key'],attempts[1].options.headers['Idempotency-Key']);});
test('unavailable product can be removed and blocks checkout',async t=>{const catalog=structuredClone(products);catalog[0].enabled=false;const p=await page(t,{catalog,saved:JSON.stringify({items:[{productId:'produto_01',quantity:1}]})});assert.equal(p.d.querySelector('[data-add-product="produto_01"]').disabled,true);assert.equal(p.d.querySelector('#cart-checkout').disabled,true);assert.match(p.d.querySelector('#cart-lines').textContent,/indisponível/);p.d.querySelector('.cart-remove').click();assert.equal(p.stored().items.length,0);});
test('unpriced catalog and missing gateway keep charge disabled',async t=>{const catalog=structuredClone(products);catalog[0].priceCents=null;const p=await page(t,{catalog,configured:false});p.add('produto_01');assert.equal(p.d.querySelector('#cart-checkout').disabled,true);assert.match(p.d.querySelector('#cart-total').textContent,/definir/);});
test('loading/network error has visible feedback and retry control',async t=>{const p=await page(t,{error:true});p.add('produto_01');assert.equal(p.d.querySelector('#cart-checkout').disabled,true);assert.match(p.d.querySelector('#cart-message').textContent,/conexão/);assert(p.d.querySelector('#cart-retry'));});
test('file preview keeps cart functional and explains backend requirement',async t=>{const p=await page(t,{offline:true});p.add('produto_01');assert.equal(p.d.querySelector('#cart-count').textContent,'1');assert.equal(p.d.querySelector('#cart-checkout').disabled,true);assert.match(p.d.querySelector('#cart-message').textContent,/servidor/);assert.equal(p.calls.length,0);});
test('storage unavailable does not break cart',()=>{const dom=new JSDOM('',{runScripts:'outside-only'});try{dom.window.eval(model);const cart=new dom.window.JewelryCartModel.Cart({getItem(){throw Error();},setItem(){throw Error();}});assert.equal(cart.add('produto_01'),true);assert.equal(cart.persisted,false);assert.equal(cart.items[0].quantity,1);}finally{dom.window.close();}});
test('original carousel, 5 devotional cards, filters, details, contact and keyboard menu preserved',async t=>{const {d,w}=await page(t);assert.equal(d.querySelectorAll('.piece').length,5);assert.equal(d.querySelectorAll('[data-add-product]').length,5);assert.equal(d.querySelectorAll('.hero-image').length,4);d.querySelector('.hero-arrow.next').click();assert.equal(d.querySelectorAll('.hero-image')[1].className,'hero-image current');d.querySelector('.hero-arrow.prev').click();assert.equal(d.querySelectorAll('.hero-image')[0].className,'hero-image current');d.querySelector('[data-filter="sao-jose"]').click();assert.equal([...d.querySelectorAll('.piece')].filter(p=>!p.hidden).length,1);d.querySelector('[data-filter="todos"]').click();d.querySelector('[data-open-piece]').click();assert.equal(d.querySelector('#modal-title').textContent,'São Jorge');d.querySelector('#ask-piece').click();assert(d.querySelector('#contact-message').value.includes('São Jorge'));d.querySelector('.menu-button').click();assert.equal(d.querySelector('.menu-button').getAttribute('aria-expanded'),'true');d.dispatchEvent(new w.KeyboardEvent('keydown',{key:'Escape'}));assert.equal(d.querySelector('.menu-button').getAttribute('aria-expanded'),'false');d.querySelector('#contact-name').value='Teste';d.querySelector('#contact-email').value='teste@example.invalid';d.querySelector('.contact-form').dispatchEvent(new w.Event('submit',{bubbles:true,cancelable:true}));assert.equal(d.querySelector('#contact-result').hidden,false);assert(d.querySelector('#message-preview').value.includes('Teste'));});
for(const status of ['pending','paid'])test(`success screen takes ${status} from backend, never URL/localStorage`,async t=>{const id=randomUUID();const dom=new JSDOM(readFileSync('frontend/sucesso.html','utf8'),{url:`https://loja.example/sucesso?orderId=${id}&status=approved&paymentStatus=paid`,runScripts:'outside-only'});t.after(()=>dom.window.close());const w=dom.window;w.eval(model);w.localStorage.setItem('jewelry.cart.v1',JSON.stringify({items:[{productId:'produto_01',quantity:1}],paymentStatus:'paid'}));w.sessionStorage.setItem('jewelry.pendingOrder',id);w.fetch=async()=>({ok:true,json:async()=>({orderId:id,status,total:19990,items:[{productId:'produto_01',name:'Peça',quantity:1,subtotal:19990}]})});w.eval(readFileSync('frontend/js/order-status.js','utf8'));await tick();assert.equal(w.document.querySelector('#order-status').textContent,status==='paid'?'Pagamento confirmado':'Aguardando pagamento');assert.equal(JSON.parse(w.localStorage.getItem('jewelry.cart.v1')).items.length,status==='paid'?0:1);});
test('success page opened without an order cannot report payment',async t=>{const dom=new JSDOM(readFileSync('frontend/sucesso.html','utf8'),{url:'https://loja.example/sucesso?status=approved',runScripts:'outside-only'});t.after(()=>dom.window.close());dom.window.eval(readFileSync('frontend/js/order-status.js','utf8'));await tick();assert.equal(dom.window.document.querySelector('#order-status').textContent,'Pagamento não confirmado');});
