(()=>{
 'use strict';
 const get=s=>document.querySelector(s),checkoutButton=get('#cart-checkout'),deliveryForm=get('#delivery-form');
 if(!checkoutButton||!deliveryForm||!window.JewelryCartModel)return;

 const css=document.createElement('link');css.rel='stylesheet';css.href='/css/pix-payment.css';document.head.append(css);
 let pixButton=null,pixBusy=false,polling=false,context=null;
 const cash=cents=>(Number(cents||0)/100).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
 const sleep=ms=>new Promise(resolve=>setTimeout(resolve,ms));
 function storageGet(key){try{return sessionStorage.getItem(key)||'';}catch{return '';}}
 function storageSet(key,value){try{sessionStorage.setItem(key,value);}catch{}}
 function storageRemove(key){try{sessionStorage.removeItem(key);}catch{}}
 async function api(path,options={}){const response=await fetch(path,{credentials:'same-origin',cache:'no-store',...options,signal:AbortSignal.timeout(20000)});let data=null;try{data=await response.json();}catch{}if(!response.ok){const error=new Error(data?.message||'Não foi possível concluir a operação.');error.code=data?.error||'request_failed';throw error;}return data;}
 function cartItems(){let storage;try{storage=localStorage;}catch{storage={getItem(){return null;},setItem(){}};}return new window.JewelryCartModel.Cart(storage).payload().items;}
 function addressData(){const fields=['cep','street','number','complement','district','city','state'];return Object.fromEntries(fields.map(key=>[key,deliveryForm.elements?.namedItem(key)?.value||'']));}
 function customerData(){return {name:get('#customer-name')?.value||'',phone:get('#customer-phone')?.value||'',email:get('#customer-email')?.value||''};}
 function setCartMessage(text){const el=get('#cart-message');if(el){el.textContent=text;el.hidden=!text;}}
 function setPixMessage(text){const el=get('#pix-payment-message');if(el){el.textContent=text;el.hidden=!text;}}
 function safeClearCart(order){try{const model=window.JewelryCartModel,current=model.clean(localStorage.getItem(model.KEY)),expected=(order.items||[]).map(({productId,quantity})=>({productId,quantity:Number(quantity)})).sort((a,b)=>a.productId.localeCompare(b.productId)),actual=[...current].sort((a,b)=>a.productId.localeCompare(b.productId));if(JSON.stringify(actual)===JSON.stringify(expected))localStorage.setItem(model.KEY,JSON.stringify({items:[]}));}catch{}const count=get('#cart-count');if(count)count.textContent='0';}
 function resetPixPanel(){context=null;polling=false;const review=get('#cart-review'),filled=get('#cart-filled');if(review)review.hidden=true;if(filled)filled.hidden=false;syncDisabled();}
 function syncDisabled(){if(pixButton)pixButton.disabled=pixBusy||checkoutButton.disabled;}
 function showPaid(order){safeClearCart(order);storageRemove('jewelry.pixAttempt.'+order.orderId);storageRemove('jewelry.cardPrepare');storageRemove('jewelry.pendingOrder');const review=get('#cart-review');review.innerHTML=`<div class="pix-result success"><span class="pix-result-icon">✓</span><h3>Pix recebido</h3><p>O pagamento foi confirmado pelo Mercado Pago.</p><p class="order-reference">Pedido #${order.orderCode||order.orderId}</p><a class="button" href="/sucesso?orderId=${encodeURIComponent(order.orderId)}">Acompanhar pedido</a></div>`;}
 function showTerminal(order){storageRemove('jewelry.pixAttempt.'+(order?.orderId||context?.prepared?.orderId||''));const labels={failed:'O Pix não foi aprovado.',cancelled:'O Pix foi cancelado ou expirou.',refunded:'O pagamento foi reembolsado.',partially_refunded:'Parte do pagamento foi reembolsada.',charged_back:'O pagamento foi contestado/estornado.',in_mediation:'O pagamento está em mediação.'};const review=get('#cart-review');review.innerHTML=`<div class="pix-result"><span class="pix-result-icon">!</span><h3>Pagamento não concluído</h3><p>${labels[order?.status]||'Confira o status do pedido antes de tentar novamente.'}</p><button type="button" id="pix-return" class="button">Voltar ao carrinho</button></div>`;get('#pix-return')?.addEventListener('click',resetPixPanel);}
 function renderQr(result){
  const pix=result.pix;if(!pix?.qrCode||!pix?.qrCodeBase64)throw new Error('O Mercado Pago não retornou um QR Code Pix válido.');
  const review=get('#cart-review'),expires=pix.expiresAt?new Date(pix.expiresAt).toLocaleString('pt-BR'):'em até 30 minutos';
  review.innerHTML=`<div class="pix-payment-head"><div><span class="pix-kicker">Pagamento instantâneo</span><h3>Pix</h3></div><button type="button" id="pix-close" class="pix-back" aria-label="Voltar ao carrinho">←</button></div><div class="pix-qr-card"><img id="pix-qr-image" alt="QR Code Pix do pedido"><p>Escaneie o QR Code no aplicativo do seu banco ou copie o código abaixo.</p><textarea id="pix-copy-code" readonly aria-label="Pix Copia e Cola"></textarea><button type="button" id="pix-copy" class="button pix-copy-button">Copiar código Pix</button>${pix.ticketUrl?`<a id="pix-ticket" class="text-link" target="_blank" rel="noopener noreferrer">Abrir Pix no Mercado Pago</a>`:''}<p class="pix-expiration">Válido até ${expires}.</p><p id="pix-payment-message" class="pix-message" role="status">Aguardando pagamento…</p><a class="text-link" href="/sucesso?orderId=${encodeURIComponent(result.orderId)}">Acompanhar pedido</a></div>`;
  get('#pix-qr-image').src='data:image/png;base64,'+pix.qrCodeBase64;get('#pix-copy-code').value=pix.qrCode;if(pix.ticketUrl)get('#pix-ticket').href=pix.ticketUrl;
  get('#pix-close').addEventListener('click',resetPixPanel);get('#pix-copy').addEventListener('click',async()=>{try{if(navigator.clipboard?.writeText)await navigator.clipboard.writeText(pix.qrCode);else{const area=get('#pix-copy-code');area.focus();area.select();document.execCommand('copy');}get('#pix-copy').textContent='Código copiado';setTimeout(()=>{const b=get('#pix-copy');if(b)b.textContent='Copiar código Pix';},1400);}catch{setPixMessage('Não foi possível copiar automaticamente. Selecione o código acima.');}});
 }
 async function pollOrder(orderId){if(polling)return;polling=true;try{for(let i=0;i<120;i++){await sleep(3000);try{const order=await api('/api/orders/'+encodeURIComponent(orderId));if(order.status==='paid'){showPaid(order);return;}if(['failed','cancelled','refunded','partially_refunded','charged_back'].includes(order.status)){showTerminal(order);return;}if(order.status==='in_mediation'){setPixMessage('O pagamento entrou em mediação. Não gere outra cobrança para este pedido.');return;}if(order.pix?.qrCode&&get('#pix-copy-code')){get('#pix-copy-code').value=order.pix.qrCode;}}catch{}}setPixMessage('O Pix continua aguardando confirmação. Use “Acompanhar pedido” para consultar novamente.');}finally{polling=false;}}
 function showPixForm(session,prepared){
  context={session,prepared};const review=get('#cart-review'),filled=get('#cart-filled');if(filled)filled.hidden=true;if(review)review.hidden=false;
  const list=(prepared.items||[]).map(item=>`<li>${Number(item.quantity||0)} × ${String(item.name||'')} — ${cash(item.subtotal)}</li>`).join('');
  review.innerHTML=`<div class="pix-payment-head"><div><span class="pix-kicker">Pagamento instantâneo</span><h3>Pagar com Pix</h3></div><button type="button" id="pix-back" class="pix-back" aria-label="Voltar ao carrinho">←</button></div><p class="cart-small"><strong>${prepared.customer?.name||''}</strong><br>${prepared.customer?.email||''}</p><ul class="pix-summary">${list}<li>${prepared.shipping?.name||'Frete'} — ${cash(prepared.shipping?.priceCents)}</li></ul><p class="pix-total">Total <strong>${cash(prepared.total)}</strong></p><form id="pix-form" class="pix-form"><div class="pix-document-grid"><label>Documento<select id="pix-identification-type"><option value="CPF">CPF</option><option value="CNPJ">CNPJ</option></select></label><label>Número<input id="pix-identification-number" inputmode="numeric" autocomplete="off" required maxlength="18" placeholder="Somente números"></label></div><button type="submit" class="button pix-generate">Gerar QR Code Pix</button><p id="pix-payment-message" class="pix-message" role="status" hidden></p></form><p class="pix-security">O valor é confirmado pelo servidor. O pedido só será considerado pago após confirmação do Mercado Pago.</p>`;
  get('#pix-back').addEventListener('click',resetPixPanel);
  get('#pix-form').addEventListener('submit',async event=>{event.preventDefault();if(pixBusy)return;const type=get('#pix-identification-type').value,number=get('#pix-identification-number').value.replace(/\D/g,'');if((type==='CPF'&&number.length!==11)||(type==='CNPJ'&&number.length!==14)){setPixMessage(`Informe ${type==='CPF'?'11':'14'} números para o ${type}.`);return;}pixBusy=true;const submit=event.currentTarget.querySelector('button[type="submit"]');submit.disabled=true;submit.textContent='Gerando Pix…';setPixMessage('Criando o QR Code com segurança…');try{const attemptStorage='jewelry.pixAttempt.'+prepared.orderId,attemptKey=storageGet(attemptStorage)||crypto.randomUUID();storageSet(attemptStorage,attemptKey);const result=await api('/api/pix/pay',{method:'POST',headers:{'Content-Type':'application/json','X-CSRF-Token':session.csrfToken,'Idempotency-Key':attemptKey},body:JSON.stringify({orderId:prepared.orderId,identification:{identificationType:type,identificationNumber:number}})});storageSet('jewelry.pendingOrder',result.orderId);if(result.status==='paid'){showPaid(result);return;}if(['failed','cancelled','refunded','partially_refunded','charged_back'].includes(result.status)){showTerminal(result);return;}renderQr(result);pollOrder(result.orderId);}catch(error){setPixMessage(error.message||'Não foi possível gerar o Pix. Tente novamente sem alterar o pedido.');submit.disabled=false;submit.textContent='Gerar QR Code Pix';}finally{pixBusy=false;syncDisabled();}});
 }
 async function beginPix(){if(pixBusy)return;if(!deliveryForm.reportValidity())return;const selected=get('input[name="shipping-choice"]:checked');if(!selected){const msg=get('#shipping-message');if(msg)msg.textContent='Selecione uma opção de entrega antes de pagar.';return;}const items=cartItems();if(!items.length)return;pixBusy=true;syncDisabled();setCartMessage('Preparando pagamento por Pix…');try{const [session,catalog]=await Promise.all([api('/api/session'),api('/api/products')]);if(!catalog.pixConfigured)throw new Error('O pagamento por Pix ainda não está disponível.');const prepared=await api('/api/pix/prepare',{method:'POST',headers:{'Content-Type':'application/json','X-CSRF-Token':session.csrfToken,'Idempotency-Key':crypto.randomUUID()},body:JSON.stringify({items,customer:customerData(),address:addressData(),quoteId:selected.value})});storageSet('jewelry.pendingOrder',prepared.orderId);showPixForm(session,prepared);setCartMessage('');}catch(error){setCartMessage(error.message||'Não foi possível abrir o pagamento por Pix.');}finally{pixBusy=false;syncDisabled();}}

 async function initialize(){try{const catalog=await api('/api/products');if(!catalog.pixConfigured)return;const wrap=document.createElement('div');wrap.className='pix-option-wrap';wrap.innerHTML='<span class="pix-or">ou</span>';pixButton=document.createElement('button');pixButton.type='button';pixButton.className='button pix-option-button';pixButton.textContent='Pagar com Pix';pixButton.addEventListener('click',beginPix);wrap.append(pixButton);checkoutButton.insertAdjacentElement('afterend',wrap);new MutationObserver(syncDisabled).observe(checkoutButton,{attributes:true,attributeFilter:['disabled']});syncDisabled();}catch{}}
 initialize();
})();
